# Coleta e preparação de dados

In [1]:
CSV_URL = 'https://caelum-online-public.s3.amazonaws.com/3056-data-visualization/relatorio_vendas.csv'

In [2]:
import pandas as pd

df = pd.read_csv(CSV_URL)

df.head()

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro
0,2018-11-09,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,encanamentos,890.66,2,142.51
1,2018-11-09,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,ferramentas,2488.60,3,746.58
2,2018-06-13,Econômica,Giovanna Lima,B2B,Rio de Janeiro,Rio de Janeiro,Sudeste,Jardinagem e paisagismo,sementes,49.71,2,23.36
3,2017-10-12,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Materiais de construção,materiais de revestimento,3255.76,5,-1302.31
4,2017-10-12,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Jardinagem e paisagismo,vasos,76.05,2,8.56

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nome_cliente      8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   cidade            8940 non-null   object
 5   estado            8940 non-null   object
 6   regiao            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_produto      8940 non-null   object
 9   vendas            8940 non-null   float64
 10  quantidade        8940 non-null   int64
 11  lucro             8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.2+ KB

In [4]:
df['data_pedido'] = pd.to_datetime(df['data_pedido'])

df.head()

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro
0,2018-11-09,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,encanamentos,890.66,2,142.51
1,2018-11-09,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,ferramentas,2488.60,3,746.58
2,2018-06-13,Econômica,Giovanna Lima,B2B,Rio de Janeiro,Rio de Janeiro,Sudeste,Jardinagem e paisagismo,sementes,49.71,2,23.36
3,2017-10-12,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Materiais de construção,materiais de revestimento,3255.76,5,-1302.31
4,2017-10-12,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Jardinagem e paisagismo,vasos,76.05,2,8.56

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nome_cliente      8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   cidade            8940 non-null   object
 5   estado            8940 non-null   object
 6   regiao            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_produto      8940 non-null   object
 9   vendas            8940 non-null   float64
 10  quantidade        8940 non-null   int64
 11  lucro             8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.2+ KB

# Missão 1: Time de vendas

Precisamos construir uma visualização para indicar os **10 maiores clientes por total de venda**.

Com isso, a equipe de vendas pode pensar em estratégias para manter esses clientes comprando em nossa loja.

In [18]:
df_cliente_vendas = df.groupby('nome_cliente')['vendas'].sum().nlargest(10).copy()
df_cliente_vendas = df_cliente_vendas.reset_index()
df_cliente_vendas

            nome_cliente    vendas
0    Maria Luiza Almeida  64777.54
1        Ana Julia Pinto  51398.95
2            Ryan Farias  48178.94
3         Heitor da Mata  47610.85
4  Maria Clara Gonçalves  46946.42
5         Raquel Freitas  44826.26
6             Davi Ramos  43769.21
7            Amanda Melo  42354.27
8         Alexia Ribeiro  41238.84
9         Calebe Ribeiro  41056.70

In [19]:
df_cliente_vendas.columns = ['Clientes', 'Vendas']
df_cliente_vendas['Rank'] = df_cliente_vendas.index + 1
df_cliente_vendas.set_index('Rank', inplace=True)
df_cliente_vendas

                   Clientes    Vendas
Rank
1       Maria Luiza Almeida  64777.54
2           Ana Julia Pinto  51398.95
3               Ryan Farias  48178.94
4            Heitor da Mata  47610.85
5     Maria Clara Gonçalves  46946.42
6            Raquel Freitas  44826.26
7                Davi Ramos  43769.21
8               Amanda Melo  42354.27
9            Alexia Ribeiro  41238.84
10           Calebe Ribeiro  41056.70

In [20]:
s = df_cliente_vendas.style
s

In [21]:
s.format({'Vendas': 'R$ {:,.2f}'})
s

# Missão 2: Time comercial

Precisamos construir uma visualização que permita associar o **total ganho em vendas e o total lucrado por tipo de produto**.

Isso vai permitir que o time comercial possa focar em estratégias para alavancar as rendas que ganham com cada tipo de produto vendido na loja.

In [22]:
df_venda_lucro = df.groupby('tipo_produto')[['vendas', 'lucro']].sum()
df_venda_lucro.index.name = 'Tipo Produto'
df_venda_lucro

                               vendas      lucro
Tipo Produto
decoração de jardim          82680.87   19880.86
encanamentos                373224.39  -11243.39
equipamentos de limpeza     542304.55   17448.30
ferramentas                 995159.43   82042.91
ferramentas automotivas     502109.33  126660.54
ferramentas de jardinagem   648880.47  106408.80
fertilizantes                53144.55   22509.86
iluminação                  275229.82   40531.09
materiais de paisagismo     150552.80   -3823.67
materiais de revestimento   629656.41  -57737.23
mobiliário de exterior      328932.37   53569.57
mudas                         8811.69    2762.88
pesticidas                  244958.41  106688.03
peças de reposição          486907.88  182297.32
pneus                      1022430.50  134923.09
sementes                     39980.49   17730.06
vasos                       696045.39   67887.28

In [23]:
estilo_produto = df_venda_lucro.style
estilo_produto

In [24]:
estilo_produto.format('R$ {:,.2f}')\
              .highlight_max(color='lightgreen')\
              .highlight_min(color='#f16165')
estilo_produto

In [25]:
estilo_produto.format('R$ {:,.2f}')\
              .background_gradient(cmap='Greens')
estilo_produto

In [26]:
header = dict(selector='th',
              props='font-weight: bold;'
                    'font-family: Arial;'
                    'text-align: center;'
                    'text-transform: capitalize;')

estilo_produto.set_table_styles([header], overwrite=False)

# Missão 3: Time de logística

Precisamos construir uma visualização que permita entender a **distribuição de pedidos por região do Brasil**.

Isso vai permitir que o time logística entenda onde é mais interessante focar material e pessoas.

In [27]:
df_regiao = pd.DataFrame(df['regiao'].value_counts())
df_regiao.columns = ['N. Pedidos']
df_regiao

              N. Pedidos
Sudeste             4470
Nordeste            2075
Centro-Oeste         983
Norte                779
Sul                  633

In [28]:
df_regiao.index.name = 'Região'

In [29]:
import numpy as np

porcentagem = df_regiao['N. Pedidos'].to_numpy()
porcentagem = 100 * porcentagem / porcentagem.sum()
porcentagem

array([50.        , 23.21029083, 10.99552573,  8.71364653,  7.08053691])

In [30]:
df_regiao['Porcentagem Região'] = porcentagem
df_regiao

              N. Pedidos  Porcentagem Região
Região
Sudeste             4470           50.000000
Nordeste            2075           23.210291
Centro-Oeste         983           10.995526
Norte                779            8.713647
Sul                  633            7.080537

In [31]:
estilo_regiao = df_regiao.style
estilo_regiao

In [32]:
header = dict(selector='th',
              props='font-weight: bold;'
                    'font-family: Arial;'
                    'text-align: right;'
                    'background-color: white;')

cell = dict(selector='td',
            props='background-color: white;')

estilo_regiao.set_table_styles([header, cell])

In [33]:
estilo_regiao.format({'Porcentagem Região': '{:,.2f} %'})\
             .bar(subset='Porcentagem Região',
                  vmin=0,
                  vmax=100.,
                  color='#9cd33b')

# Missão 4: Time de logística

Novamente o time de logística deseja repensar sua estrutura e organização de fornecimento de produtos e para isso, foi pensada em uma visualização que permita identificar padrão de **quantidade de produtos solicitados por mês por departamento**.

In [6]:
df_meses = df.copy()

df_meses = df_meses.sort_values('data_pedido')

df_meses.head()

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro
7171,2016-01-04,Entrega padrão,Ana Júlia Monteiro,B2C,Belo Horizonte,Minas Gerais,Sudeste,Jardinagem e paisagismo,pesticidas,55.92,2,18.87
651,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,12.04,2,-18.66
650,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,vasos,927.30,3,-220.23
649,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,sementes,40.07,3,14.52
1576,2016-01-06,Entrega padrão,Marcelo Rezende,B2C,Brasília,Distrito Federal,Centro-Oeste,Jardinagem e paisagismo,decoração de jardim,66.42,3,16.61

In [7]:
df_meses['meses'] = df_meses['data_pedido'].dt.strftime('%Y - %d')

df_meses = df_meses.reset_index(drop=True)

df_meses.head()

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro,meses
0,2016-01-04,Entrega padrão,Ana Júlia Monteiro,B2C,Belo Horizonte,Minas Gerais,Sudeste,Jardinagem e paisagismo,pesticidas,55.92,2,18.87,2016 - 04
1,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,12.04,2,-18.66,2016 - 05
2,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,vasos,927.30,3,-220.23,2016 - 05
3,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,sementes,40.07,3,14.52,2016 - 05
4,2016-01-06,Entrega padrão,Marcelo Rezende,B2C,Brasília,Distrito Federal,Centro-Oeste,Jardinagem e paisagismo,decoração de jardim,66.42,3,16.61,2016 - 06

In [8]:
vendas_mensais = df_meses.pivot_table(index='departamento',
                                      columns='meses',
                                      values='quantidade',
                                      aggfunc='sum',
                                      sort=False)

vendas_mensais

meses,2016 - 04,2016 - 05,2016 - 06,2016 - 07,2016 - 08,2016 - 10,2016 - 11,2016 - 12,2016 - 14,2016 - 15,...,2019 - 30,2019 - 31,2019 - 05,2019 - 06,2019 - 07,2019 - 11,2019 - 12,2019 - 18,2019 - 19,2019 - 26
departamento,,,,,,,,,,,,,,,,,,,,,
Jardinagem e paisagismo,129,131,182,122,142,184,78,156,137,150,...,155,123,163,217,214,164,228,262,288,215
Automotivo,20,32,35,32,28,49,34,72,36,43,...,16,36,63,55,36,77,58,92,69,43
Materiais de construção,30,28,30,45,55,52,26,74,23,46,...,71,49,63,47,46,51,54,73,72,89

In [9]:
estilo_mensal = vendas_mensais.style

estilo_mensal

In [10]:
estilo_mensal.set_sticky(axis='index')

In [11]:
colunas = dict(selector='.col_heading',
               props='font-weight:normal;font-family:Arial;')

tabelas = dict(selector='td,th',
               props='text-align:left;')

index = dict(selector='.index_name',
             props='font-weight:bold;font-family:Arial;text-align:right')

estilo_mensal.set_table_styles([colunas, tabelas, index], overwrite=False)

# Missão 5: Relatório de performance

O relatório de performance é um documento muito importante para a empresa. Nele, todos que trabalham na loja podem entender como anda a empresa. Por conta disso, tabelas bem construídas são essenciais para mostrar os dados da melhor forma.

Portanto, precisamos construir uma visualização que permita entender a **relação entre tipos de clientes e modo de envio de produtos de acordo com as vendas**. Com isso, será possível destacar no relatório qual o modo de envio e quais tipos de modo de envio mais geraram ganho em vendas.

In [12]:
df_cliente = df.pivot_table(index='segmento_cliente',
                            columns='modo_envio',
                            values='vendas',
                            aggfunc='sum')

df_cliente

modo_envio         24 horas  Econômica  Entrega padrão  Envio rápido
segmento_cliente
B2B               217466.05  718462.52      1884740.78     602049.56
B2C               182531.80  729176.13      2248286.96     498295.55

In [13]:
df_cliente['Total'] = df_cliente.sum(axis=1)

df_cliente.loc['Total'] = df_cliente.sum()

df_cliente

modo_envio,24 horas,Econômica,Entrega padrão,Envio rápido,Total
segmento_cliente,,,,,
B2B,217466.05,718462.52,1884740.78,602049.56,3422718.91
B2C,182531.80,729176.13,2248286.96,498295.55,3658290.44
Total,399997.85,1447638.65,4133027.74,1100345.11,7081009.35

In [14]:
compra_cliente = df_cliente.style.format('{:,.2f}')

compra_cliente

In [15]:
tabela = dict(selector='td,th:not(.index_name)',
              props='font-weight:normal;font-family:Arial;text-align:center;background-color: grey;')

index = dict(selector='.index_name',
             props='font-weight: normal; text-align: rigth; font-style: italic; color: #696969')

compra_cliente.set_table_styles([tabela, index])

In [16]:
compra_cliente.set_table_styles({
    'Total': [
        {
            'selector': 'th',
            'props': 'border-top:1px solid #181818'
        },
        {
            'selector': 'td',
            'props': 'border-top: 1px solid #181818'
        }
    ],
    'B2B': [
        {
            'selector': 'td',
            'props': 'border-top: 1px solid #181818 '
        },
        {
            'selector': 'td',
            'props': 'border-top: 1px solid #181818 '
        }
    ]
}, overwrite=False, axis=1)

In [17]:
compra_cliente.set_table_styles({
    'Total': [
        {
            'selector': '.true',
            'props': 'background-color: #D8D8D8'
        }
    ]
}, overwrite=False, axis=0)